import type { Metadata } from "next";
import { Playfair_Display, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";


// 1. Cấu hình Font Serif sang trọng cho tiêu đề (Hỗ trợ subset vietnamese)
const playfair = Playfair_Display({
  subsets: ["vietnamese"],
  variable: "--font-serif", // Tạo một biến CSS variable
  weight: ["400", "500", "600", "700"],
});

// 2. Cấu hình Font Sans-serif cho nội dung text thông thường
const jakarta = Plus_Jakarta_Sans({
  subsets: ["vietnamese"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${playfair.variable} ${jakarta.variable}`}
    >
      <head>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&amp;family=Playfair+Display:wght@600;700&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&amp;display=swap" rel="stylesheet"/></head>
      <body className="min-h-full flex flex-col"><Header/>{children}</body>
    </html>
  );
}
